image: ubuntu:latest

stages:
  - build
  - test
  # - smell-detection
  # - deploy

cache:
  paths:
    - node_modules/
    - .m2/repository/

# before_script:
#   - apt-get update && apt-get install -y curl
#   - curl -sL https://deb.nodesource.com/setup_14.x | bash -
#   - apt-get install -y nodejs
#   - apt-get install -y maven


build-backend:
  stage: build
  image: maven:latest
  tags:
    - v1
  script:
    - cd backend/creator-connect
    - echo "Running build stage (backend)..."
    - chmod +x ./mvnw
    - ./mvnw -version
    - cat /etc/os-release
    - ./mvnw clean package
    - java -version
    - echo "Build successful!"

test-backend:
  stage: test
  image: maven:latest
  tags:
    - v1
  script:
    - cd backend/creator-connect
    - echo "Running test stage..."
    - chmod +x ./mvnw
    - ./mvnw test
    - echo "Test stage completed!"

build-frontend:
  stage: build
  image: node:16
  #tags:
  #  - v1
  script:
    - cd frontend/creator-connect
    - echo "Building frontend..."
    - npm install
    - npm run build
    - echo "Build successful!"


# code-quality:
#   stage: smell-detection
#   tags:
#     - v1.0
#   script:
#     - echo "Code quality stage..."
#     - wget "https://www.designite-tools.com/static/download/DJE/DesigniteJava.jar"
#     - java -jar DesigniteJava.jar -i backend/creatorconnect -o backend/creatorconnect
#     - echo "Saving results in csvs..."
#   artifacts:
#     paths:
#       - ArchitectureSmells.csv
#       - DesignSmells.csv
#       - ImplementationSmells.csv
#       - MethodMetrics.csv
#       - TestabilitySmells.csv
#       - TypeMetrics.csv

# deploy-backend:
#   stage: deploy
#   tags:
#     - v1.0
#   script:
#     - cd backend/creatorconnect
#     - mvn clean package
#     - echo "Building docker image..."
#     - docker build -t creator_connect_backend .
#     - echo "Deploying backend on docker..."
#     - docker run -d -p 8080:8080 creator_connect_backend

# deploy-frontend:
#   stage: deploy
#   tags:
#     - v1.0
#   script:
#     - cd CreatorConnect/frontend
#     -
